import "./globals.css";

export const metadata = {
  title: "Module-9",
  description: "Generated by create next.js & react.js app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="w-3/6 m-auto">{children}</div>
      </body>
    </html>
  );
}
