import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = true;
  return (
    <html lang="en">
      <body
        className={`bg-[#030613]
          ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
