import { Inter } from "next/font/google";

import "@/style/globals.css";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hello Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="py-3 border border-red-600 text-center">Header</h1>
        {children}
        <h1 className="py-3 border border-red-600 text-center">Footer</h1>
      </body>
    </html>
  );
}
