import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Foooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Module-8",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Navbar />
        <div className="w-3/5 m-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
