export const actions = {
  author: {
    DATA_FETCHING: "AUTHOR_DATA_FETCHING",
    DATA_FETCHED: "AUTHOR_DATA_FETCHED",
    DATA_FETCH_ERROR: "AUTHOR_DATA_FETCH_ERROR",
    AUTHOR_DATA_EDITED: "AUTHOR_DATA_EDITED",
    IMAGE_UPDATED: "AUTHOR_IMAGE_UPDATED",
  },
  blog: {
    DATA_FETCHING: "BLOG_DATA_FETCHING",
    DATA_FETCHED: "BLOG_DATA_FETCHED",
    DATA_FETCH_ERROR: "BLOG_DATA_FETCH_ERROR",
    DATA_CREATED: "BLOG_DATA_CREATED",
    DATA_EDITED: "BLOG_DATA_EDITED",
    BLOG_DELETED: "BLOG_DATA_DELETED",
  },
};
