import "./globals.css";

export const metadata = {
  title: "Module-13",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-cyan-100" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
